[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
temp_project = "iNPdYUArjLu2a9YzHPYeeWrGaoEJqTc2p6EANMR84dh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/initialize.ts" 
register-user = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/register_user.ts" 
rent-car = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/rent_car.ts" 
end-rent = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/end_rent.ts" 
add-car = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/add_car.ts" 
deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/deposit.ts" 
withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/withdraw.ts" 

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE"